# Generated by Django 4.2.3 on 2023-07-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Tdate',
            field=models.DateField(default='2023-12-20'),
            preserve_default=False,
        ),
    ]
